### ISSUE TITLE
Misclassidication of stacked system

### ISSUE THREAD

**Issue by TheaDene** [SINGROUP/matid#10]
The single surface is correctly classified as `<Classification.Surface: '2D Surface'>`, but the same surface twice as a stacked system is classified as `<Classification.Class2D: '2D Generic'>`. 

The command `clusters[1].cell()` returns `*** AttributeError: 'NoneType' object has no attribute 'cell'` for the stacked system.

**Comment by lauri-codes** [comment]
@TheaDene: Could you try the newest version in `develop`? If the problem persists could you send the the structure file.

**Comment by TheaDene** [comment]
@lauri-codes: Yes. Now  `clusters[2].cell()` returns the cell information but the surfaces are still classified as` <Classification.Class2D: '2D Generic'>`.
