### ISSUE TITLE
Further development and plans?

### ISSUE THREAD

**Issue by blokhin** [SINGROUP/matid#4]
Good day Lauri,

it was very interesting for me to learn about `matid`! Many years ago I actually did [something similar](https://github.com/tilde-lab/tilde/tree/master/tilde/classifiers), on a less serious level although. In future I'd be definitely willing to re-use `matid`. Here are some questions I'd like to ask:
- What is your general vision concerning the further development? _e.g._ do you plan to interface and support other Python materials libraries such as `AiiDA`, `pymatgen` _etc._?
- Do you plan to consider more concrete structural classes? _i.e._ detection of the `perovskites`, `spinels`, `schorls`, `Friauf-Laves` types, `adamantanes`, which is of course very useful and scientifically interesting, but difficult task.
- In my experience I've encountered some really philosophical questions about the classification. Consider _e.g._ VASP calculation of a molecule box, when the distance between the replicas is just a couple of Å. Should it be considered as 3D or 0D? There are the other more complicated examples with the 2D adsorption and so on. What is your approach?

In whole, thanks for your efforts, they are really appreciated!

**Comment by lauri-codes** [comment]
Hi Evgeny!

Thanks for your interest in `matid`.

1. I'm still maintaining the software and it is actively being used within NOMAD to perform structural classification for the entries that are processed. `matid` is fairly agnostic with respect to what framework or library is used to call it. As long as your data can be turned into ase.Atoms, you can also work with `matid`.

2. Something like this is definitely possible to some extent, as long as the classification does not require knowledge about the functional properties of the material. I actually have some code that can be used to connect bulk structures to the corresponding [AFLOW prototypes](http://www.aflowlib.org/CrystalDatabase/) (these prototypes contain at least some spinels and perovskites). If this is something of interest to you I can integrate it into `matid`.

3. This is certainly true. My approach so far has been to expose parameters that the users can then adjust to their liking. E.g. the size of the vacuum gap to separate 3D from 0D. Some of these classification boundaries would require detailed knowledge about the energetics of the system, which then depend on the used method as well. So, for now, I don't see any very good universal way out of this problem.
